version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: plataforma-aluno-plus
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www/

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: plataforma-aluno-plus-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
  
  mysql:
    image: mysql:latest
    container_name: mysql-student-plus-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_plus
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-student-plus:/var/lib/mysql
volumes:
  mysql-data-student-plus: