version: "3.8"

services:
  php_apache:
    container_name: student-plus-php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mysql
    extra_hosts:
      - "mysql:172.18.0.2"

  mysql:
    image: mysql:latest
    container_name: mysql-student-plus-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_plus
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-student-plus:/var/lib/mysql
    networks:
      - network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "php_apache:172.18.0.3"

networks:
  network:
    driver: bridge

volumes:
  mysql-data-student-plus:
